In [6]:
import pandas as pd

In [34]:
df = pd.read_csv(r'/Users/thispc/Documents/Orders (Global Superstore)_Migrated Data.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [43]:
df = pd.read_csv(
    r'/Users/thispc/Documents/Orders (Global Superstore)_Migrated Data.csv',
    encoding='utf-16',
    delimiter='\t'  # Adjust to the correct delimiter
)

In [44]:
df

,Category,City,Country,Customer ID,Market,market,Order Date,Order ID,Order Priority,Product ID,...,Ship Date,Ship Mode,State,Sub-Category,Discount,Number of Records,Profit,Quantity,Sales,Shipping Cost
0,Office Supplies,Budapest,Hungary,AT-7352,EMEA,EMEA,01/01/2011,HU-2011-1220,High,OFF-TEN-10001585,...,05/01/2011,Second Class,Budapest,Storage,0.00,1,29.6400,4,66.1200,8.17
1,Office Supplies,Stockholm,Sweden,EM-141402,EU,EU,01/01/2011,IT-2011-3647632,High,OFF-PA-10001492,...,05/01/2011,Second Class,Stockholm,Paper,0.50,1,-26.0550,3,44.8650,4.82
2,Office Supplies,Constantine,Algeria,TB-112801,Africa,Africa,01/01/2011,AG-2011-2040,Medium,OFF-TEN-10000025,...,06/01/2011,Standard Class,Constantine,Storage,0.00,1,106.1400,2,408.3000,35.46
3,Furniture,Wagga Wagga,Australia,JH-159851,APAC,APAC,01/01/2011,IN-2011-47883,Medium,FUR-FU-10003447,...,08/01/2011,Standard Class,New South Wales,Furnishings,0.10,1,37.7700,5,113.6700,4.70
4,Office Supplies,Wagga Wagga,Australia,JH-159851,APAC,APAC,01/01/2011,IN-2011-47883,Medium,OFF-PA-10001968,...,08/01/2011,Standard Class,New South Wales,Paper,0.10,1,15.3420,2,55.2420,1.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,Office Supplies,Columbus,United States,CC-124304,North America,US,31/12/2014,CA-2014-126221,Medium,OFF-AP-10002457,...,06/01/2015,Standard Class,Indiana,Appliances,0.00,1,56.5110,2,209.3000,8.32
51286,Technology,Surabaya,Indonesia,MH-177851,APAC,APAC,31/12/2014,IN-2014-78228,Medium,TEC-PH-10004402,...,06/01/2015,Standard Class,Jawa Timur,Phones,0.17,1,88.4208,4,293.6208,13.57
51287,Office Supplies,Shantou,China,KM-162251,APAC,APAC,31/12/2014,IN-2014-23754,Medium,OFF-EN-10002630,...,07/01/2015,Standard Class,Guangdong,Envelopes,0.00,1,24.7500,5,67.2000,4.06
51288,Office Supplies,Shantou,China,KM-162251,APAC,APAC,31/12/2014,IN-2014-23754,Medium,OFF-PA-10004727,...,07/01/2015,Standard Class,Guangdong,Paper,0.00,1,25.3800,3,79.4700,1.41
51289,Technology,Shantou,China,KM-162251,APAC,APAC,31/12/2014,IN-2014-23754,Medium,TEC-AC-10002324,...,07/01/2015,Standard Class,Guangdong,Accessories,0.00,1,6.8400,3,171.9900,16.66

In [48]:
df2 = pd.read_csv('/Users/thispc/Documents/Sales by Rep_Migrated Data.csv',encoding='utf-16',delimiter='\t')

In [49]:
df2

,Country,Deal ID,Sales Rep,Number of Records,Sales,Year of Transaction Date
0,Benin,US-2014-125213,Nona Balk,1,6.540,2014
1,Benin,AG-2012-170,Philip Fox,1,198.210,2012
2,Benin,BN-2014-9200,Philip Fox,1,1187.160,2014
3,Benin,CA-2012-101707,Philip Fox,1,150.220,2012
4,Benin,CA-2012-111458,Philip Fox,1,50.000,2012
...,...,...,...,...,...,...
271950,Spain,IN-2014-61792,Mitch Webber,1,4191.507,2014
271951,Spain,MX-2012-100461,Mitch Webber,1,148.800,2012
271952,Spain,MX-2012-104276,Mitch Webber,1,15.060,2012
271953,Spain,MX-2012-134341,Mitch Webber,1,385.420,2012
271954,Spain,MX-2012-164007,Mitch Webber,1,42.160,2012

In [ ]:
def word_count(sentences):
    sentences = sentences.replace('\n', ' ')
    word_count = {}
    char_count = {}
    words = sentences.split(' ')
    for word in words:
        if word in word_count:
            word_count[word] +=1
        else:
            word_count[word] = 1
        for char in word.strip():
            if char in char_count:
                char_count[char] +=1
            else:
                char_count[char] = 1 
    return word_count,char_count
    
    


sentences = """Operational Excellence Pillar

The operational excellence pillar focuses on running and monitoring systems, and continually improving processes and procedures. Key topics include automating changes, responding to events, and defining standards to manage daily operations."""
word,result = word_count(sentences)
print(result)
print(word)